package Project;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.GregorianCalendar;
import java.util.Iterator;

public class AddServiceForm extends MotorcycleApp {

    private JPanel panel1;
    private JRadioButton dealerServiceRadio;
    private JRadioButton selfServiceRadio;
    private JTextField serviceDateTextBox;
    private JTextPane serviceDescriptionText;
    private JComboBox motorcycleDropdown;
    private JButton serviceSubmitButton;
    private int selected;

    public AddServiceForm() {


        $$$setupUI$$$();
        motorcycleDropdown.addActionListener(this);

        JTextArea output = new JTextArea();

        output.setText("Motorcycle Details:\n\n");

        if (AddServiceForm.super.motorcycles.size() < 1) {
            JOptionPane.showMessageDialog(null, "No motorcycles have been added to the system", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            for (Motorcycle motorcycle : AddServiceForm.super.motorcycles) {
                motorcycleDropdown.addItem(motorcycle.getModelName() + "\n");
            }
            selected = motorcycleDropdown.getSelectedIndex();
        }

        serviceSubmitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                Service serviceToAdd = new Service();

                selected = motorcycleDropdown.getSelectedIndex();

                boolean dealerService;

                if (dealerServiceRadio.isSelected()) {
                    dealerService = true;
                } else {
                    dealerService = false;
                }

                if (dealerService) {
                    serviceToAdd.setDealerOrSelf("Dealer Service");
                } else {
                    serviceToAdd.setDealerOrSelf("Self Service");
                }

                serviceToAdd.setServiceNotes(serviceDescriptionText.getText());
                serviceToAdd.setServiceDate(AddServiceForm.super.getDateString(serviceDateTextBox.getText()));

                for (int i = 0; i < AddServiceForm.super.motorcycles.get(selected).getServiceHistory().length; i++) {

                    if (AddServiceForm.super.motorcycles.get(selected).getServiceHistory()[i] == null) {
                        AddServiceForm.super.motorcycles.get(selected).getServiceHistory()[i] = serviceToAdd;

                        i = AddServiceForm.super.motorcycles.get(selected).getServiceHistory().length;
                    }
                }

                try {
                    AddServiceForm.super.save();
                    AddServiceForm.super.closeServiceFrame();
                } catch (IOException ioException) {
                    ioException.printStackTrace();
                }
            }
        });
    }

    public JPanel getPanel1() {
        return panel1;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 1));
        panel2.setMinimumSize(new Dimension(300, 32));
        panel2.setPreferredSize(new Dimension(316, 20));
        panel2.putClientProperty("html.disable", Boolean.FALSE);
        panel1.add(panel2, BorderLayout.CENTER);
        motorcycleDropdown = new JComboBox();
        panel2.add(motorcycleDropdown);
        dealerServiceRadio = new JRadioButton();
        dealerServiceRadio.setText("Dealer Service");
        panel2.add(dealerServiceRadio);
        selfServiceRadio = new JRadioButton();
        selfServiceRadio.setText("Self Service");
        panel2.add(selfServiceRadio);
        final JLabel label1 = new JLabel();
        label1.setText("Service Date");
        panel2.add(label1);
        serviceDateTextBox = new JTextField();
        serviceDateTextBox.setPreferredSize(new Dimension(55, 30));
        panel2.add(serviceDateTextBox);
        serviceSubmitButton = new JButton();
        serviceSubmitButton.setText("Submit");
        panel2.add(serviceSubmitButton);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        panel3.setPreferredSize(new Dimension(19, 365));
        panel1.add(panel3, BorderLayout.SOUTH);
        panel3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        serviceDescriptionText = new JTextPane();
        panel3.add(serviceDescriptionText, BorderLayout.CENTER);
        final JLabel label2 = new JLabel();
        label2.setText("   Enter Service Notes Below");
        panel3.add(label2, BorderLayout.NORTH);


    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
